### ISSUE TITLE
VPK installation fails (Code 0x8010113D)

### ISSUE THREAD

**Issue by GrJT** [SonicMastr/renpy-vita#12]
I have compiled my game with the Distribution Tool. When I try to install it on my Vita through VitaShell, the installation goes through until 99%, where it gets stuck for a bit, then fails with the error code in the title.
Details: 
* --I'm running the program through Wine in Ubuntu, Linux. I'm not sure if this causes any interference.-- UPDATE: Tried it on a Windows PC with another project, the problem persisted.
* The game contains images directed for an Android distribution. (Splash, icon...)
* I haven't modified anything of the game, I made it for Windows and Android. Though I don't believe that has anything to do with this problem, it happens during installation.
* For the LiveArea images, I just put gray (corresponding) PNGs made in an image editor. Without any special modification.
* I have tested with both compiled (.rpa files) and uncompiled (just the raw project and files) builds/games.

**Comment by snivez-git** [comment]
i'm also having this issue, and i hope the developer looks into this

**Comment by GZT028** [comment]
0x8010113D = trying to install a package that has livearea images that were not run through pngquant 

Just drag and drop the images on the pngquant.exe and you shoud recive a output in the same folder with a fs8 suffix,
rename it to:icon0, pic0, bg0,  or startup 


sce_sys
│   icon0.png -  128x128 bubble icon
│   pic0.png -   960x544  picture before in game menu
│
└───livearea
    └───contents
            bg0.png - 840x500  bacground of the "paper"
            startup.png - 280x158  picture that shown above the "Start"/"Resume"  the only file support trasparency
            template.xml -   markup file that indicates what elements and where to place them in the "paper" menu

**Comment by GrJT** [comment]
@GZT028 
Thanks a lot for your answer. I had the wrong resolution for the `pic0.png`...
Though, I'd like to point out some tips about your answer that I've noticed:

- While the name `bg0.png` is used in most guides, this program requires the name `bg.png`.
- I'm pretty sure LiveArea images are already passed through pngquant when exporting through Ren'Py PSVita Distribution Tool.
