### ISSUE TITLE
Crash of Everlasting Summer...

### ISSUE THREAD

**Issue by SergoPSP** [SonicMastr/renpy-vita#5]
Hello. Is it possible to port Everlasting Summer on PS Vita? I tried myself... But... There error. 
![DH7gUkVBS2k](https://user-images.githubusercontent.com/77193193/136708805-284965db-613c-417e-81c7-e21f496b6fc9.jpg)

**Comment by mrdivdiz** [comment]
Same here with issue #3 - forced quit.Tried 1.3 and 1.4 versions of the game.

**Comment by mrdivdiz** [comment]
@SergoPSP Russian?Давай-ка совместно соберем этот порт.

**Comment by SergoPSP** [comment]
okay, now it works

**Comment by d0ctr** [comment]
@SergoPSP @mrdivdiz I have tried packaging ES 1.2 with current release of Distribution tool, but it still stuck on the loading splash screen. Do you have a working VPK?

**Comment by R3Skako** [comment]
> okay, now it works

@SergoPSP 
sorry for necroing, but what was the solution????
