### ISSUE TITLE
Can't build VPK on Wine

### ISSUE THREAD

**Issue by Auster-South-Anemoi** [SonicMastr/renpy-vita#7]
.NET is installed from this file: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.0-windows-x64-installer

After supplying all the files the program was asking for and filling the required fields, the "Build VPK" button is still greyed out.

Any clue of what I'm doing wrong?

I also didn't understand the instructions for compiling the program for Linux, thus I went for the Windows version emulated on Wine.

**Comment by SonicMastr** [comment]
The Distribution Tool will not allow you to build a VPK if the format of your provided information is not correct. Check the hints of the input fields for proper formatting. 

An incorrectly formatted param.sfo file can cause errors while installing VPKs which is why that check is there

**Comment by Auster-South-Anemoi** [comment]
I think I managed to find out what was the issue:
The Vita normally has game IDs starting with 4 letters and followed by 5 numbers, and I was trying some random game ID (something like GAME4VITA).
I'll test it some more later, but for now, it seems to be compiling the game I'm using to test.

**Comment by Auster-South-Anemoi** [comment]
And yes, just like the hint suggested, although I didn't notice at first.
